name: telegram-app
version: 1
summary: A Telegram client
description: |
  This Telegram client is based on the Ubuntu SDK
confinement: devmode

apps:
  telegram-app:
    command: bin/telegram-app.wrapper
    plugs: [network-bind]

parts:
    libqtelegram-ae:
      plugin: qmake
      qt-version: qt5
      source-type: git
      source: https://github.com/Aseman-Land/libqtelegram-aseman-edition.git
      options:
        - -r
        - PREFIX=/usr
    telegramqml:
      plugin: qmake
      qt-version: qt5
      source-type: git
      source: https://github.com/Aseman-Land/TelegramQML.git
      after: [libqtelegram-ae]
      options:
        - -r
        - PREFIX=/usr
        - BUILD_MODE+=lib
        - DEFINES+=UBUNTU_PHONE
        - INCLUDEPATH+=/usr/include/thumbnailer-qt-1.0/unity/thumbnailer/qt
        - LIBQTELEGRAM_INCLUDE_PATH=$SNAPCRAFT_STAGE/usr/include/libqtelegram-ae
        - LIBS+=-lthumbnailer-qt
      build-packages:
        - libthumbnailer-qt-dev
    telegram-app:
      plugin: qmake
      qt-version: qt5
      source-type: bzr
      source: lp:~jocave/telegram-app/snapping-fixes
      source-subdir: telegram
      after: [telegramqml]
      options:
        - -r
        - PREFIX=/usr
        - INCLUDEPATH+=/usr/include/thumbnailer-qt-1.0/unity/thumbnailer/qt
        - INCLUDEPATH+=$SNAPCRAFT_STAGE/usr/include/libqtelegram-ae
        - INCLUDEPATH+=$SNAPCRAFT_STAGE/usr/include/telegramqml
      build-packages:
        - libthumbnailer-qt-dev
      stage-packages:
        - ubuntu-sdk-libs
        - qtubuntu-desktop
        - qml-module-ubuntu-connectivity
        - qtdeclarative5-ubuntu-contacts0.1
      snap:
        - -usr/share/doc
        - -usr/include
    environment:
      plugin: copy
      files:
        telegram-app.wrapper: bin/telegram-app.wrapper
        snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf
